version: "3"
services:

  postgres:
    container_name: postgres-container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: vk_users
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  vowpal-wabbit:
    container_name: vowpal-wabbit-container
    image: vowpalwabbit/ubuntu1604-build
    restart: always
    ports:
    - 58000:58000

  vowpal-wabbit-run:
    container_name: vowpal-wabbit-run
    depends_on:
      - vowpal-wabbit
    restart: always
    build:
      context: .
      dockerfile: Docker-vowel

  service:
    container_name: api-container
    depends_on:
      - postgres
      - vowpal-wabbit
    build:
      context: .
      dockerfile: Dockerfile
    command: ./service
    env_file:
      - .env
    ports:
      - 8080:8080