version: "3"
services:

  postgres:
    container_name: postgres-container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: sites

  postgres-adminer:
    container_name: postgres-adminer-container
    image: adminer
    restart: always
    ports:
      - 8081:8081

  service:
    container_name: api-container
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    command: ./service
    env_file:
      - .env
    ports:
      - 8080:8080