version: "3"
services:

  postgres:
    container_name: postgres-container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: vk_users
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  service:
    container_name: api-container
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    command: ./service
    env_file:
      - .env
    ports:
      - 8080:8080